### ISSUE TITLE
Mbed CLI doesn't correctly handle target detection during `mbed dm update device -D <id> -m DETECT`

### ISSUE THREAD

**Issue by screamerbg** [ARMmbed/mbed-cli#791]
See title

```
mbed dm update device -D 01671d2e968c0000000000010010038c -m DETECT -t ARM
[mbed] Auto-installing missing Python modules...
Traceback (most recent call last):
  File "D:\Work\smcc-example\mbed-os\tools\device_management.py", line 178, in <module>
    main()
  File "D:\Work\smcc-example\mbed-os\tools\device_management.py", line 173, in main
    }[options.action](options) or 0
  File "D:\Work\smcc-example\mbed-os\tools\device_management.py", line 79, in inner
    mcus = extract_mcus(MbedExtendedArgs(), options)
  File "D:\Work\smcc-example\mbed-os\tools\options.py", line 137, in extract_mcus
    args_error(parser, "argument -m/--mcu: {}".format(str(exc)))
  File "D:\Work\smcc-example\mbed-os\tools\utils.py", line 319, in args_error
    parser.error(message)
AttributeError: 'MbedExtendedArgs' object has no attribute 'error'
[mbed] ERROR: "c:\progra~1\python\python.exe" returned error.
       Code: 1
       Path: "D:\Work\smcc-example"
       Command: "c:\progra~1\python\python.exe -u D:\Work\smcc-example\mbed-os\tools\device_management.py update device -D 01671d2e968c0000000000010010038c --toolchain ARM --mcu DETECT --build .\BUILD\DETECT\ARM"
       Tip: You could retry the last command with "-v" flag for verbose output
```

CC @theotherjimmy

**Comment by theotherjimmy** [comment]
Yep. Good catch.

**Comment by ciarmcom** [comment]
*Internal Jira reference: https://jira.arm.com/browse/MBOCUSTRIA-172*

**Comment by BlackstoneEngineering** [comment]
Any chance we could get this fixed? It'd make it a hellova lot easier to do tutorials if we had the `-m auto` command. Also can we make sure that it'll check the environment / global config if none is provided?

**Comment by ciarmcom** [comment]
Thank you for raising this issue. Please note we have updated our policies and 
 now only defects should be raised directly in GitHub. Going forward questions and 
 enhancements will be considered in our forums, https://forums.mbed.com/ . If this 
 issue is still relevant please re-raise it there.
 This GitHub issue will now be closed.

**Comment by adbridge** [comment]
Apologies, this was closed in error by the automated bot - re-opening.

**Comment by ciarmcom** [comment]
*Internal Jira reference: https://jira.arm.com/browse/IOTBTOOL-469*

**Comment by AshUK** [comment]
`mbed dm update device -D <device_id> -m <CUSTOM TARGET> -t ARM_GCC`

This command also fails when specifying a custom target
