### ISSUE TITLE
mbedls failing (5.13.2 mbed-os, 1.10.1 mbed-cli) on macOS

### ISSUE THREAD

**Issue by petertorelli** [ARMmbed/mbed-cli#908]
I just upgraded from an old mbed-cli 0.0.10 version to the new .dmg installer, and now I'm having issues programming and interacting with my boards.

Here's the output. I can include debug output, but it is quite large. I also included the USB port list so you can see the CMSIS device is present (also registers a volume). Suggestions?

```
% mbedls
Traceback (most recent call last):
  File "/Applications/MBEDCLI.app/Contents/Resources/miniconda/bin/mbedls", line 11, in <module>
    sys.exit(mbedls_main())
  File "/Applications/MBEDCLI.app/Contents/Resources/miniconda/lib/python2.7/site-packages/mbed_lstools/main.py", line 194, in mbedls_main
    ret_code = args.command(mbeds, args)
  File "/Applications/MBEDCLI.app/Contents/Resources/miniconda/lib/python2.7/site-packages/mbed_lstools/main.py", line 60, in print_table
    return print_mbeds(mbeds, args, False)
  File "/Applications/MBEDCLI.app/Contents/Resources/miniconda/lib/python2.7/site-packages/mbed_lstools/main.py", line 47, in print_mbeds
    devices = mbeds.list_mbeds(unique_names=True, read_details_txt=True)
  File "/Applications/MBEDCLI.app/Contents/Resources/miniconda/lib/python2.7/site-packages/mbed_os_tools/detect/lstools_base.py", line 153, in list_mbeds
    device["target_id_usb_id"][0:4],
TypeError: 'NoneType' object has no attribute '__getitem__'
1 ✗ [11:29:52 Thu Aug 15] ~/mbed/mbed-os-example-blinky
% mbed --version
1.10.0
% ioreg -p IOUSB
+-o Root  <class IORegistryEntry, id 0x100000100, retain 15>
  +-o AppleUSBXHCI Root Hub Simulation@14000000  <class AppleUSBRootHubDevice, id 0x10000030f, registered, matched, active, busy 0 (520 ms), retain 12>
    +-o BRCM20702 Hub@14300000  <class AppleUSBDevice, id 0x100000311, registered, matched, active, busy 0 (554 ms), retain 12>
    | +-o Bluetooth USB Host Controller@14330000  <class AppleUSBDevice, id 0x10000037c, registered, matched, active, busy 0 (580 ms), retain 17>
    +-o Apple Internal Keyboard / Trackpad@14400000  <class AppleUSBDevice, id 0x100000322, registered, matched, active, busy 0 (607 ms), retain 15>
    +-o USB2.0 Hub@14100000  <class AppleUSBDevice, id 0x100002201, registered, matched, active, busy 0 (487 ms), retain 13>
    | +-o USB2.0 Hub             @14140000  <class AppleUSBDevice, id 0x100002246, registered, matched, active, busy 0 (486 ms), retain 13>
    | | +-o Logitech USB Headset H540@14143000  <class AppleUSBDevice, id 0x100002273, registered, matched, active, busy 0 (552 ms), retain 17>
    | | +-o USB2.0 Hub             @14144000  <class AppleUSBDevice, id 0x10000227f, registered, matched, active, busy 0 (485 ms), retain 13>
    | |   +-o YubiKey OTP+FIDO+CCID@14144400  <class AppleUSBDevice, id 0x1000022bc, registered, matched, active, busy 0 (494 ms), retain 21>
    | |   +-o Goldtouch USB Keyboard@14144100  <class AppleUSBDevice, id 0x1000022e7, registered, matched, active, busy 0 (321 ms), retain 13>
    | +-o MBED CMSIS-DAP@14130000  <class AppleUSBDevice, id 0x10000282d, registered, matched, active, busy 0 (68 ms), retain 17>
    +-o USB3.0 Hub@14500000  <class AppleUSBDevice, id 0x100002215, registered, matched, active, busy 0 (487 ms), retain 12>
      +-o USB3.0 Hub             @14540000  <class AppleUSBDevice, id 0x10000225c, registered, matched, active, busy 0 (487 ms), retain 12>
        +-o USB3.0 Hub             @14544000  <class AppleUSBDevice, id 0x1000022b1, registered, matched, active, busy 0 (709 ms), retain 11>

```

**Comment by petertorelli** [comment]
Aaaaand closing: my device firmware is not mbed 5 compliant.
