### ISSUE TITLE
mbed dm init not working - cannot import python_2_unicode_compatible

### ISSUE THREAD

**Issue by gggekov** [ARMmbed/mbed-cli#971]
Hi,

I want to try a firmware update, using mbed-cli version 1.10.2 and python 2.7.15+ in Ubuntu18.  
The error I am getting is:
```
george@ubuntu:~/repo/mbed-os-example-pelion$ mbed dm init -d "Arm" --model-name "product_name"
[mbed] Working path "/home/george/repo/mbed-os-example-pelion" (program)
Traceback (most recent call last):
  File "/home/george/repo/mbed-os-example-pelion/mbed-os/tools/device_management.py", line 27, in <module>
    from manifesttool import create, parse, verify, cert, init, update
  File "/home/george/.local/lib/python2.7/site-packages/manifesttool/create.py", line 19, in <module>
    from manifesttool.v1.create import main as create_v1
  File "/home/george/.local/lib/python2.7/site-packages/manifesttool/v1/create.py", line 20, in <module>
    import codecs, hashlib, sys, json, os, base64, binascii, logging, ecdsa, uuid
  File "/home/george/.local/lib/python2.7/site-packages/ecdsa/__init__.py", line 1, in <module>
    from .keys import SigningKey, VerifyingKey, BadSignatureError, BadDigestError,\
  File "/home/george/.local/lib/python2.7/site-packages/ecdsa/keys.py", line 72, in <module>
    from . import ecdsa
  File "/home/george/.local/lib/python2.7/site-packages/ecdsa/ecdsa.py", line 57, in <module>
    from . import ellipticcurve
  File "/home/george/.local/lib/python2.7/site-packages/ecdsa/ellipticcurve.py", line 49, in <module>
    from six import python_2_unicode_compatible
ImportError: cannot import name python_2_unicode_compatible
[mbed] ERROR: "/usr/bin/python" returned error.
       Code: 1
       Path: "/home/george/repo/mbed-os-example-pelion"
       Command: "/usr/bin/python -u /home/george/repo/mbed-os-example-pelion/mbed-os/tools/device_management.py init -d Arm --model-name product_name"
       Tip: You could retry the last command with "-v" flag for verbose output
---

```
How can this be fixed? `pip install -U mbed-cli` didn't help.

**Comment by gggekov** [comment]
Installing the `mbed-os` requirements results in a segmentation fault:
```
george@ubuntu:~/repo/mbed-os-example-pelion$ pip install -r mbed-os/requirements.txt 
Ignoring hidapi: markers 'platform_system != "Linux"' don't match your environment
Ignoring pywin32: markers 'platform_system == "Windows"' don't match your environment
Ignoring wmi: markers 'platform_system == "Windows"' don't match your environment
Collecting colorama==0.3.9 (from -r mbed-os/requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/db/c8/7dcf9dbcb22429512708fe3a547f8b6101c0d02137acbd892505aee57adf/colorama-0.3.9-py2.py3-none-any.whl
Collecting urllib3[secure]==1.24.2 (from -r mbed-os/requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/df/1c/59cca3abf96f991f2ec3131a4ffe72ae3d9ea1f5894abe8a9c5e3c77cfee/urllib3-1.24.2-py2.py3-none-any.whl
Collecting prettytable==0.7.2 (from -r mbed-os/requirements.txt (line 3))
Collecting junit-xml==1.8 (from -r mbed-os/requirements.txt (line 4))
Collecting pyyaml==4.2b1 (from -r mbed-os/requirements.txt (line 5))
Collecting jsonschema==2.6.0 (from -r mbed-os/requirements.txt (line 6))
  Using cached https://files.pythonhosted.org/packages/77/de/47e35a97b2b05c2fadbec67d44cfcdcd09b8086951b331d82de90d2912da/jsonschema-2.6.0-py2.py3-none-any.whl
Collecting future==0.16.0 (from -r mbed-os/requirements.txt (line 7))
Collecting six==1.12.0 (from -r mbed-os/requirements.txt (line 8))
  Using cached https://files.pythonhosted.org/packages/73/fb/00a976f728d0d1fecfe898238ce23f502a721c0ac0ecfedb80e0d88c64e9/six-1.12.0-py2.py3-none-any.whl
Collecting mbed-cloud-sdk<2.1,>=2.0.6 (from -r mbed-os/requirements.txt (line 9))
  Using cached https://files.pythonhosted.org/packages/50/34/4bc3b0efe5d4cb56fba71535ef16c607f7ce125d80841a3e2b2e9962df44/mbed_cloud_sdk-2.0.8-py2.py3-none-any.whl
Collecting requests<2.21,>=2.20 (from -r mbed-os/requirements.txt (line 10))
  Using cached https://files.pythonhosted.org/packages/ff/17/5cbb026005115301a8fb2f9b0e3e8d32313142fe8b617070e7baad20554f/requests-2.20.1-py2.py3-none-any.whl
Collecting idna<2.8,>=2 (from -r mbed-os/requirements.txt (line 11))
  Using cached https://files.pythonhosted.org/packages/4b/2a/0276479a4b3caeb8a8c1af2f8e4355746a97fab05a372e4a2c6a6b876165/idna-2.7-py2.py3-none-any.whl
Collecting pyserial<=3.4,>=3 (from -r mbed-os/requirements.txt (line 12))
  Using cached https://files.pythonhosted.org/packages/0d/e4/2a744dd9e3be04a0c0907414e2a01a7c88bb3915cbe3c8cc06e209f59c30/pyserial-3.4-py2.py3-none-any.whl
Collecting Jinja2<2.11,>=2.10.1 (from -r mbed-os/requirements.txt (line 13))
  Using cached https://files.pythonhosted.org/packages/65/e0/eb35e762802015cab1ccee04e8a277b03f1d8e53da3ec3106882ec42558b/Jinja2-2.10.3-py2.py3-none-any.whl
Collecting intelhex<=2.2.1,>=1.3 (from -r mbed-os/requirements.txt (line 14))
  Using cached https://files.pythonhosted.org/packages/bf/77/bf670318b3db325c71e2ac6a90b7bcfdf9fc739b7cf6aebb31715721623e/intelhex-2.2.1-py2.py3-none-any.whl
Collecting mbed-ls<1.8,>=1.5.1 (from -r mbed-os/requirements.txt (line 15))
  Using cached https://files.pythonhosted.org/packages/8e/2c/72855a353999cad5ff6ef13120ef60eb1cbc3112ecdd5a02fdd022e22236/mbed_ls-1.7.10-py2.py3-none-any.whl
Collecting mbed-host-tests<1.6,>=1.4.4 (from -r mbed-os/requirements.txt (line 16))
  Using cached https://files.pythonhosted.org/packages/7f/94/1e727eb5955341a23ac892326ef3d8c1544202b13453f57c09d48e78b307/mbed_host_tests-1.5.10-py2.py3-none-any.whl
Collecting mbed-greentea<1.8,>=0.2.24 (from -r mbed-os/requirements.txt (line 17))
  Using cached https://files.pythonhosted.org/packages/85/9f/8336a68476298eabdd405123ebbfec802f71a89610f52e92d52fcfaf30ea/mbed_greentea-1.7.4-py2.py3-none-any.whl
Collecting beautifulsoup4<=4.6.3,>=4 (from -r mbed-os/requirements.txt (line 18))
  Using cached https://files.pythonhosted.org/packages/f8/c7/741c97d7366f4779ca73d244904978b43a81fd37d85fcf05ad19d472c1ce/beautifulsoup4-4.6.3-py2-none-any.whl
Collecting pyelftools<=0.25,>=0.24 (from -r mbed-os/requirements.txt (line 19))
  Using cached https://files.pythonhosted.org/packages/b8/45/00776dc25dc2ad0573d48c2d86f2d4a554216d00bf4575423557f5a398ca/pyelftools-0.25-py2.py3-none-any.whl
Collecting manifest-tool==1.5.2 (from -r mbed-os/requirements.txt (line 20))
Collecting icetea<1.3,>=1.2.1 (from -r mbed-os/requirements.txt (line 21))
Collecting pycryptodome<=3.7.3,>=3.7.2 (from -r mbed-os/requirements.txt (line 22))
  Using cached https://files.pythonhosted.org/packages/29/68/0ee43d649a2f748f805c427558e3ec8d832faa34ca1f369195b274266e1d/pycryptodome-3.7.3-cp27-cp27mu-manylinux1_x86_64.whl
Collecting pyusb<2.0.0,>=1.0.0 (from -r mbed-os/requirements.txt (line 23))
Collecting cmsis-pack-manager<0.3.0,>=0.2.3 (from -r mbed-os/requirements.txt (line 25))
  Using cached https://files.pythonhosted.org/packages/01/2d/631ba8f2eaffff4862fef21aa7399ed1c1f976b75089502fad26629dfa54/cmsis_pack_manager-0.2.10-py2.py3-none-manylinux1_x86_64.whl
Collecting psutil==5.6.2 (from -r mbed-os/requirements.txt (line 28))
Collecting cryptography<2.5,>=2.4.x (from -r mbed-os/requirements.txt (line 29))
  Using cached https://files.pythonhosted.org/packages/7f/ba/383b51cc26e3141c689ce988814385c7659f5ba01c4b5f2de38233010b5f/cryptography-2.4.2-cp27-cp27mu-manylinux1_x86_64.whl
Collecting Click<7.1,>=7.0 (from -r mbed-os/requirements.txt (line 30))
  Using cached https://files.pythonhosted.org/packages/fa/37/45185cb5abbc30d7257104c434fe0b07e5a195a6847506c074527aa599ec/Click-7.0-py2.py3-none-any.whl
Collecting pyOpenSSL>=0.14; python_version == "2.7" and extra == "secure" (from urllib3[secure]==1.24.2->-r mbed-os/requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/9e/de/f8342b68fa9e981d348039954657bdf681b2ab93de27443be51865ffa310/pyOpenSSL-19.1.0-py2.py3-none-any.whl
Collecting ipaddress; python_version == "2.7" and extra == "secure" (from urllib3[secure]==1.24.2->-r mbed-os/requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/c2/f8/49697181b1651d8347d24c095ce46c7346c37335ddc7d255833e7cde674d/ipaddress-1.0.23-py2.py3-none-any.whl
Collecting certifi; extra == "secure" (from urllib3[secure]==1.24.2->-r mbed-os/requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/57/2b/26e37a4b034800c960a00c4e1b3d9ca5d7014e983e6e729e33ea2f36426c/certifi-2020.4.5.1-py2.py3-none-any.whl
Collecting functools32; python_version == "2.7" (from jsonschema==2.6.0->-r mbed-os/requirements.txt (line 6))
Collecting python-dotenv>=0.8.2 (from mbed-cloud-sdk<2.1,>=2.0.6->-r mbed-os/requirements.txt (line 9))
  Using cached https://files.pythonhosted.org/packages/cb/2a/07f87440444fdf2c5870a710b6770d766a1c7df9c827b0c90e807f1fb4c5/python_dotenv-0.13.0-py2.py3-none-any.whl
Collecting python-dateutil>=2 (from mbed-cloud-sdk<2.1,>=2.0.6->-r mbed-os/requirements.txt (line 9))
  Using cached https://files.pythonhosted.org/packages/d4/70/d60450c3dd48ef87586924207ae8907090de0b306af2bce5d134d78615cb/python_dateutil-2.8.1-py2.py3-none-any.whl
Collecting chardet<3.1.0,>=3.0.2 (from requests<2.21,>=2.20->-r mbed-os/requirements.txt (line 10))
  Using cached https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl
Collecting MarkupSafe>=0.23 (from Jinja2<2.11,>=2.10.1->-r mbed-os/requirements.txt (line 13))
  Using cached https://files.pythonhosted.org/packages/fb/40/f3adb7cf24a8012813c5edb20329eb22d5d8e2a0ecf73d21d6b85865da11/MarkupSafe-1.1.1-cp27-cp27mu-manylinux1_x86_64.whl
Collecting mbed-os-tools<0.1.0,>=0.0.9 (from mbed-ls<1.8,>=1.5.1->-r mbed-os/requirements.txt (line 15))
  Using cached https://files.pythonhosted.org/packages/0f/9d/c2cf2b747a3a14f9433bbeefa47118a7cc27e066ac897d7025f66a8d143f/mbed_os_tools-0.0.13-py2.py3-none-any.whl
Collecting ecdsa>=0.13 (from manifest-tool==1.5.2->-r mbed-os/requirements.txt (line 20))
  Using cached https://files.pythonhosted.org/packages/b8/11/4b4d30e4746584684c758d8f1ddc1fa5ab1470b6bf70bce4d9b235965e99/ecdsa-0.15-py2.py3-none-any.whl
Collecting protobuf<3.6.0,>=3.5.0 (from manifest-tool==1.5.2->-r mbed-os/requirements.txt (line 20))
  Using cached https://files.pythonhosted.org/packages/9d/61/54c3a9cfde6ffe0ca6a1786ddb8874263f4ca32e7693ad383bd8cf935015/protobuf-3.5.2.post1-cp27-cp27mu-manylinux1_x86_64.whl
Collecting pyasn1<0.3.0,>=0.2.1 (from manifest-tool==1.5.2->-r mbed-os/requirements.txt (line 20))
  Using cached https://files.pythonhosted.org/packages/a5/ae/6b4c4cb9420edddd7401782f55504130d1269f2e5ae3ba3c986da167dd6c/pyasn1-0.2.3-py2.py3-none-any.whl
Collecting pyparsing>=2.1.0 (from manifest-tool==1.5.2->-r mbed-os/requirements.txt (line 20))
  Using cached https://files.pythonhosted.org/packages/8a/bb/488841f56197b13700afd5658fc279a2025a39e22449b7cf29864669b15d/pyparsing-2.4.7-py2.py3-none-any.whl
Collecting asn1ate>=0.5 (from manifest-tool==1.5.2->-r mbed-os/requirements.txt (line 20))
Collecting mbed-flasher<0.11,>=0.10.1 (from icetea<1.3,>=1.2.1->-r mbed-os/requirements.txt (line 21))
Collecting semver>=2.0 (from icetea<1.3,>=1.2.1->-r mbed-os/requirements.txt (line 21))
  Using cached https://files.pythonhosted.org/packages/cb/48/009529f08dd0f71262a229f0a7948dd5d27eb0e0a9edc74e6e6860ff2925/semver-2.9.1-py2.py3-none-any.whl
Collecting jsonmerge>=1.4 (from icetea<1.3,>=1.2.1->-r mbed-os/requirements.txt (line 21))
Collecting yattag>=1.0 (from icetea<1.3,>=1.2.1->-r mbed-os/requirements.txt (line 21))
Collecting appdirs>=1.4 (from cmsis-pack-manager<0.3.0,>=0.2.3->-r mbed-os/requirements.txt (line 25))
  Using cached https://files.pythonhosted.org/packages/56/eb/810e700ed1349edde4cbdc1b2a21e28cdf115f9faf263f6bbf8447c1abf3/appdirs-1.4.3-py2.py3-none-any.whl
Collecting milksnake>=0.1.2 (from cmsis-pack-manager<0.3.0,>=0.2.3->-r mbed-os/requirements.txt (line 25))
  Using cached https://files.pythonhosted.org/packages/27/be/e10e73f857ac98ef43587fa8db37a3ef6de56e728037a7b9728de26711c7/milksnake-0.1.5-py2.py3-none-any.whl
Collecting enum34; python_version < "3" (from cryptography<2.5,>=2.4.x->-r mbed-os/requirements.txt (line 29))
  Using cached https://files.pythonhosted.org/packages/6f/2c/a9386903ece2ea85e9807e0e062174dc26fdce8b05f216d00491be29fad5/enum34-1.1.10-py2-none-any.whl
Collecting asn1crypto>=0.21.0 (from cryptography<2.5,>=2.4.x->-r mbed-os/requirements.txt (line 29))
  Using cached https://files.pythonhosted.org/packages/e9/51/1db4a60049fb7390959be586b6eb743098e6cea3f6b2d3ed9e17fec62ba2/asn1crypto-1.3.0-py2.py3-none-any.whl
Collecting cffi!=1.11.3,>=1.7 (from cryptography<2.5,>=2.4.x->-r mbed-os/requirements.txt (line 29))
  Using cached https://files.pythonhosted.org/packages/08/29/8001b940ef40e7a25ffe8f3188bc9b118934b513d64f769dbf461e46f4ed/cffi-1.14.0-cp27-cp27mu-manylinux1_x86_64.whl
Collecting typing; python_version < "3.5" (from python-dotenv>=0.8.2->mbed-cloud-sdk<2.1,>=2.0.6->-r mbed-os/requirements.txt (line 9))
  Using cached https://files.pythonhosted.org/packages/22/30/64ca29543375759dc589ade14a6cd36382abf2bec17d67de8481bc9814d7/typing-3.7.4.1-py2-none-any.whl
Collecting fasteners (from mbed-os-tools<0.1.0,>=0.0.9->mbed-ls<1.8,>=1.5.1->-r mbed-os/requirements.txt (line 15))
  Using cached https://files.pythonhosted.org/packages/18/bd/55eb2d6397b9c0e263af9d091ebdb756b15756029b3cededf6461481bc63/fasteners-0.15-py2.py3-none-any.whl
Collecting lockfile (from mbed-os-tools<0.1.0,>=0.0.9->mbed-ls<1.8,>=1.5.1->-r mbed-os/requirements.txt (line 15))
  Using cached https://files.pythonhosted.org/packages/c8/22/9460e311f340cb62d26a38c419b1381b8593b0bb6b5d1f056938b086d362/lockfile-0.12.2-py2.py3-none-any.whl
Collecting setuptools (from protobuf<3.6.0,>=3.5.0->manifest-tool==1.5.2->-r mbed-os/requirements.txt (line 20))
  Using cached https://files.pythonhosted.org/packages/ab/b5/3679d7c98be5b65fa5522671ef437b792d909cf3908ba54fe9eca5d2a766/setuptools-44.1.0-py2.py3-none-any.whl
Collecting pycparser (from cffi!=1.11.3,>=1.7->cryptography<2.5,>=2.4.x->-r mbed-os/requirements.txt (line 29))
  Using cached https://files.pythonhosted.org/packages/ae/e7/d9c3a176ca4b02024debf82342dab36efadfc5776f9c8db077e8f6e71821/pycparser-2.20-py2.py3-none-any.whl
Collecting monotonic>=0.1 (from fasteners->mbed-os-tools<0.1.0,>=0.0.9->mbed-ls<1.8,>=1.5.1->-r mbed-os/requirements.txt (line 15))
  Using cached https://files.pythonhosted.org/packages/ac/aa/063eca6a416f397bd99552c534c6d11d57f58f2e94c14780f3bbf818c4cf/monotonic-1.5-py2.py3-none-any.whl
Installing collected packages: colorama, enum34, idna, asn1crypto, pycparser, cffi, six, ipaddress, cryptography, pyOpenSSL, certifi, urllib3, prettytable, junit-xml, pyyaml, functools32, jsonschema, future, typing, python-dotenv, chardet, requests, python-dateutil, mbed-cloud-sdk, pyserial, MarkupSafe, Jinja2, intelhex, beautifulsoup4, appdirs, monotonic, fasteners, lockfile, mbed-os-tools, mbed-ls, mbed-host-tests, mbed-greentea, pyelftools, ecdsa, setuptools, protobuf, pyasn1, pyparsing, asn1ate, manifest-tool, mbed-flasher, semver, jsonmerge, yattag, icetea, pycryptodome, pyusb, milksnake, cmsis-pack-manager, psutil, Click
Successfully installed Click-7.0 Jinja2-2.10.3 MarkupSafe-1.1.1 appdirs-1.4.3 asn1ate-0.6.0 asn1crypto-1.3.0 beautifulsoup4-4.9.0 certifi-2020.4.5.1 cffi-1.14.0 chardet-3.0.4 cmsis-pack-manager-0.2.10 colorama-0.4.3 cryptography-2.7 ecdsa-0.15 enum34-1.1.10 fasteners-0.15 functools32-3.2.3.post2 future-0.18.2 icetea-1.2.4 idna-2.9 intelhex-2.2.1 ipaddress-1.0.23 jsonmerge-1.7.0 jsonschema-2.6.0 junit-xml-1.9 lockfile-0.12.2 manifest-tool-1.5.2 mbed-cloud-sdk-2.0.8 mbed-flasher-0.10.1 mbed-greentea-1.7.4 mbed-host-tests-1.5.10 mbed-ls-1.7.10 mbed-os-tools-0.0.13 milksnake-0.1.5 monotonic-1.5 prettytable-0.7.2 protobuf-3.5.2.post1 psutil-5.6.2 pyOpenSSL-19.1.0 pyasn1-0.2.3 pycparser-2.20 pycryptodome-3.7.3 pyelftools-0.25 pyparsing-2.4.7 pyserial-3.4 python-dateutil-2.8.1 python-dotenv-0.13.0 pyusb-1.0.2 pyyaml-4.2b1 requests-2.23.0 semver-2.9.1 setuptools-44.1.0 six-1.14.0 typing-3.7.4.1 urllib3-1.25.9 yattag-1.13.2
Segmentation fault (core dumped)

```
Note that I am doing this from a freshly set up Virtual Machine. I expected it would work.

**Comment by ciarmcom** [comment]
Thank you for raising this detailed GitHub issue. I am now notifying our internal issue triagers. 
*Internal Jira reference: https://jira.arm.com/browse/IOTBTOOL-671*

**Comment by gggekov** [comment]
Managed to solve the issue by using python3.
