### ISSUE TITLE
Experiencing problems in installing mbed-CLI manually on Windows 10

### ISSUE THREAD

**Issue by FIssiki** [ARMmbed/mbed-cli#985]
> @woobagooba We are still looking at this issue, but it currently appears to be 
> related to the Python installation. 
> _Originally posted by @j3hill in https://github.com/ARMmbed/mbed-cli/issues/883#issuecomment-482596694_

Thank you for the support. 
I am also experiencing problems in installing mbed-CLI manually on Windows 10 (x64).
I would be glad if you allow me to comment on it, although the cause of the issue might not be the same. 

I am trying installing mbed-CLI on native Windows 10.
I am anxious if the error might be caused due to the change of the default setup of the newest releases of Python 3 (https://www.python.org/) for Windows. 

In my PC, Python 3.8.5 (x32), git 2.12.2, and Mercurial 5.5.1 (x32) are installed and working fine. 
The module "pip" was separately installed and also working. 
Importing "sys", "setuptools", "tokenize" is successful,
but the installer seems to be failing in installing mbed-CLI. 

I just followed the instruction in the "Manual installation" section on the page: 
https://os.mbed.com/docs/mbed-os/v6.2/build-tools/install-and-set-up.html

The log was:
---
C:\Users\myName\Desktop> python3 -m pip install mbed-cli
Collecting mbed-cli
  Using cached mbed_cli-1.10.4-py2.py3-none-any.whl (41 kB)
Collecting pyserial<4.0,>=3.0
  Using cached pyserial-3.4-py2.py3-none-any.whl (193 kB)
Collecting mbed-os-tools<0.1.0,>=0.0.9
  Using cached mbed-os-tools-0.0.15.tar.gz (286 kB)
Collecting requests<3.0,>=2.0
  Using cached requests-2.24.0-py2.py3-none-any.whl (61 kB)
Collecting intelhex<3.0,>=2.0
  Using cached intelhex-2.2.1-py2.py3-none-any.whl (50 kB)
Collecting future
  Using cached future-0.18.2.tar.gz (829 kB)
    ERROR: Command errored out with exit status 1:
     command: 'C:\myPyPath\python385\python3.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\myName\\AppData\\Local\\Temp\\pip-install-z14anbbi\\future\\setup.py'"'"'; __file__='"'"'C:\\Users\\myName\\AppData\\Local\\Temp\\pip-install-z14anbbi\\future\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\myName\AppData\Local\Temp\pip-pip-egg-info-4v4m8iqh'
         cwd: C:\Users\myName\AppData\Local\Temp\pip-install-z14anbbi\future\
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\myName\AppData\Local\Temp\pip-install-z14anbbi\future\setup.py", line 86, in <module>
        import src.future
    ModuleNotFoundError: No module named 'src'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

C:\Users\myName\Desktop>
---

The log seems it's failing installing mbed-CLI when it's importing "src.future" or resolving the path. 

The installer automatically cleaned the temporary files and directories when it detected failing in the installation, then I could not trace the reason further with the remained files. 

I would be glad if you would suggest what I should have checked.

**Comment by ciarmcom** [comment]
Thank you for raising this detailed GitHub issue. I am now notifying our internal issue triagers. 
*Internal Jira reference: https://jira.arm.com/browse/IOTBTOOL-975*
