### ISSUE TITLE
Problem during compilation

### ISSUE THREAD

**Issue by benoitgoyet** [ARMmbed/mbed-cli#988]
Hi,

I had to reset my computer. And I can(t succeed on compiling using mbed cli.
It used to work before reset, but not any more...

I get the following error message : 
`[mbed] Working path "/Users/goyetbenoit/Documents/10_PROGRAMATION/troporteur" (program)
Traceback (most recent call last):
  File "/Users/goyetbenoit/Documents/10_PROGRAMATION/troporteur/mbed-os/tools/make.py", line 30, in <module>
    from tools.utils import args_error
  File "/Users/goyetbenoit/Documents/10_PROGRAMATION/troporteur/mbed-os/tools/utils.py", line 32, in <module>
    from intelhex import IntelHex
  File "/usr/local/lib/python3.9/site-packages/intelhex/__init__.py", line 44, in <module>
    from intelhex.compat import (
  File "/usr/local/lib/python3.9/site-packages/intelhex/compat.py", line 60, in <module>
    array_tobytes = getattr(array.array, "tobytes", array.array.tostring)
AttributeError: type object 'array.array' has no attribute 'tostring'
[mbed] ERROR: "/usr/local/opt/python@3.9/bin/python3.9" returned error.
       Code: 1
       Path: "/Users/goyetbenoit/Documents/10_PROGRAMATION/troporteur"
       Command: "/usr/local/opt/python@3.9/bin/python3.9 -u /Users/goyetbenoit/Documents/10_PROGRAMATION/troporteur/mbed-os/tools/make.py -t ARM -m NUCLEO_L432KC --source . --build ./BUILD/NUCLEO_L432KC/ARM"
       Tip: You could retry the last command with "-v" flag for verbose output`

Does anyone has some idea?
Thanks.

**Comment by SWW13** [comment]
The issue is related to python 3.9 and does already effect some other projects for example: https://github.com/tensorflow/tensorflow/issues/45164, https://github.com/home-assistant/core/issues/41617.
It's an already fixed bug in intelhex (https://github.com/python-intelhex/intelhex/issues/45), updating the dependency should fix the problem. (It also can be used as workaround for the issue)

@benoitgoyet I'm not allowed to update the issue, could you please update the title to something like `Python 3.9 Issue with old intelhex version`?
